### ISSUE TITLE
Struts 6.0.0 support

### ISSUE THREAD

**Issue by boris-petrov** [struts-community-plugins/struts2-bootstrap#48]
I upgraded my app to Struts 6.0.0 and running it lead to:

```
05:25:17.235 [https-openssl-apr-443-exec-5] ERROR freemarker.runtime - Error executing FreeMarker template
freemarker.core._MiscTemplateException: Template inclusion failed (for parameter value "/template/~~~bootstrap/controlheader-core.ftl"):
Syntax error in template "template/~~~bootstrap/controlheader-core.ftl" in line 51, column 44:
Using ?html (legacy escaping) is not allowed when auto-escaping is on with a markup output format (HTML), to avoid double-escaping mistakes.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #include "/${parameters.templateDir}/...  [in template "template/~~~bootstrap/controlheader.ftl" at line 21, column 1]
        - Reached through: #include "/${parameters.templateDir}/...  [in template "template/bootstrap/text.ftl" at line 21, column 1]
----
        at freemarker.core.Include.accept(Include.java:164)
        at freemarker.core.Environment.visit(Environment.java:347)
        at freemarker.core.Environment.visit(Environment.java:353)
        at freemarker.core.Environment.include(Environment.java:2955)
        at freemarker.core.Include.accept(Include.java:171)
        at freemarker.core.Environment.visit(Environment.java:347)
        at freemarker.core.Environment.visit(Environment.java:353)
        ...
```

I guess the issue is with [Tag escape behaviour](https://cwiki.apache.org/confluence/display/WW/Struts+2.5+to+6.0.0+migration#Struts2.5to6.0.0migration-Tagescapebehaviour).

**Comment by znejedly** [comment]
Hi Boris: Thanks for opening a new issue - I am getting the same Freemarker error after an upgrade from 2.5.30 to 6.0.0 with struts2-bootstrap-plugin v4. Cheers, Zdenek

**Comment by ghost** [comment]
I have the same problem - thanks for raising the issue.

**Comment by jogep** [comment]
New version 5.0.0 is released based on Struts 6.0.0 and support for the freemarker version.

**Comment by gpfjeff** [comment]
I don't believe this issue has been resolved. We are in the process of upgrading to Struts 6, and we are getting the same issue as reported above.

Struts Bootstrap Plugin version: 5.0.0
Versions of Struts Core attempted: 6.0.0, 6.0.3, 6.1.1

We seem to be getting the same error regardless of which version of Struts we're using.

```
11:25:12.271 [http-nio-8080-exec-1] ERROR freemarker.runtime - Error executing FreeMarker template
freemarker.core._MiscTemplateException: Template inclusion failed (for parameter value "/template/~~~bootstrap/controlheader-core.ftl"):
Syntax error in template "template/~~~bootstrap/controlheader-core.ftl" in line 46, column 35:
Using ?html (legacy escaping) is not allowed when auto-escaping is on with a markup output format (HTML), to avoid double-escaping mistakes.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #include "/${parameters.templateDir}/...  [in template "template/~~~bootstrap/controlheader.ftl" at line 21, column 1]
	- Reached through: #include "/${parameters.templateDir}/...  [in template "template/bootstrap/text.ftl" at line 21, column 1]
----
	at freemarker.core.Include.accept(Include.java:164)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.include(Environment.java:2955)
	at freemarker.core.Include.accept(Include.java:171)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
	at org.apache.struts2.components.template.FreemarkerTemplateEngine.renderTemplate(FreemarkerTemplateEngine.java:154)
	at org.apache.struts2.components.UIBean.mergeTemplate(UIBean.java:588)
	at org.apache.struts2.components.UIBean.end(UIBean.java:547)
	at org.apache.struts2.views.jsp.ComponentTagSupport.doEndTag(ComponentTagSupport.java:40)
	[ Snipped for bevity... ]
Caused by: freemarker.core.ParseException: Syntax error in template "template/~~~bootstrap/controlheader-core.ftl" in line 46, column 35:
Using ?html (legacy escaping) is not allowed when auto-escaping is on with a markup output format (HTML), to avoid double-escaping mistakes.
	at freemarker.core.FMParser.BuiltIn(FMParser.java:1225)
	at freemarker.core.FMParser.PrimaryExpression(FMParser.java:595)
	at freemarker.core.FMParser.UnaryExpression(FMParser.java:707)
	at freemarker.core.FMParser.MultiplicativeExpression(FMParser.java:822)
	at freemarker.core.FMParser.AdditiveExpression(FMParser.java:774)
	at freemarker.core.FMParser.RangeExpression(FMParser.java:950)
	at freemarker.core.FMParser.RelationalExpression(FMParser.java:902)
	at freemarker.core.FMParser.EqualityExpression(FMParser.java:865)
	at freemarker.core.FMParser.AndExpression(FMParser.java:1017)
	at freemarker.core.FMParser.OrExpression(FMParser.java:1039)
	at freemarker.core.FMParser.Expression(FMParser.java:552)
	at freemarker.core.FMParser.StringOutput(FMParser.java:1674)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:3968)
	at freemarker.core.FMParser.If(FMParser.java:1792)
	at freemarker.core.FMParser.FreemarkerDirective(FMParser.java:3629)
	at freemarker.core.FMParser.MixedContentElements(FMParser.java:4019)
	at freemarker.core.FMParser.Root(FMParser.java:4665)
	at freemarker.template.Template.<init>(Template.java:252)
	at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:548)
	at freemarker.cache.TemplateCache.getTemplateInternal(TemplateCache.java:439)
	at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:292)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2836)
	at freemarker.core.Environment.getTemplateForInclusion(Environment.java:2913)
	at freemarker.core.Include.accept(Include.java:162)
	... 95 common frames omitted
```

Please reopen this ticket and investigate.

**Comment by lukaszlenart** [comment]
The whole work have been covered in #39 - I'm just testing struts2-bootstrap-showcase app and everything is fine, could you double check that your using proper JAR versions?

**Comment by gpfjeff** [comment]
From our maven POM:

```
<dependency>
	<groupId>org.apache.struts</groupId>
	<artifactId>struts2-core</artifactId>
	<version>6.1.1</version>
</dependency>

<dependency>
	<groupId>com.jgeppert.struts2.bootstrap</groupId>
	<artifactId>struts2-bootstrap-plugin</artifactId>
	<version>5.0.0</version>
	<exclusions>
		<exclusion>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

The exclusion on Freemarker is because Struts already brings in Freemarker 2.3.31, while Bootstrap Plugin was looking for 2.3.29. One of the first "fixes" I tried before finding this bug issue was to add the `incompatible_improvements` setting to our Freemarker properties file, but nothing I tried seemed to change anything. I've also tried removing the exclusion and still get the error.

As previously stated, I also tried downgrading Struts to 6.0.3 and 6.0.0 with the same results.

**Comment by lukaszlenart** [comment]
Could you remove that exclusion? The bootstrap plugin doesn't depend on the Freemarker, it uses Struts Core which depends on the Freemarker. And please provide result of running `mvn dependency:tree`

**Comment by lukaszlenart** [comment]
Another thing is the report - if you check line 51 of the [controlheader-core.ftl](https://github.com/struts-community-plugins/struts2-bootstrap/blob/release/5.0.x/struts2-bootstrap-plugin/src/main/resources/template/bootstrap/controlheader-core.ftl#L51) there is no `?html` in there, as well in the whole file.

That's why I assume your are using an old version - maybe try clean temp folder of your servlet container as documented in the [migration guide](https://cwiki.apache.org/confluence/display/WW/Struts+2.5+to+6.0.0+migration#Struts2.5to6.0.0migration-Temp/WorkdirectoryofApplicationServer/ServletContainer)

**Comment by gpfjeff** [comment]
My sincere apologies. You can ignore this "new" error report. It appears that, buried deep in the resources of this ancient project, some past developer overrode some of the templates, probably to work around some other ancient bug. Sure enough, the `?html` was coming from there. When I removed the override templates, the error went away. (Wouldn't be the first time I've taken a name in vain of a past maintainer of an app I've inherited...)

**Comment by lukaszlenart** [comment]
@gpfjeff great to know that everything is fine :)
